version: '3'
services:
  mongodb:
    image: mongo
    container_name: my-health-and-gym-db
    environment:
      MONGO_INITDB_DATABASE: my-health-and-gym-db
    ports:
      - "27017:27017"
  my_health_and_gym:
    build: .
    container_name: my-health-and-gym-app
    ports:
      - "8080:8080"
    depends_on:
      - mongodb
